import type { Metadata } from "next";
import "../styles/globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ChakraProvider } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "MathCha",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
