import type { Metadata } from "next";
import "../styles/globals.css";


export const metadata: Metadata = {
  title: "MathCha",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
